# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metadatos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='metadatos.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fmetadatos.proto\"j\n\tdataAvion\x12\x11\n\taerolinea\x18\x01 \x01(\t\x12\x0e\n\x06\x63odigo\x18\x02 \x01(\t\x12\x0f\n\x07pesoMax\x18\x03 \x01(\x05\x12\x11\n\tCapTanque\x18\x04 \x01(\x05\x12\x16\n\x0eipTorreInicial\x18\x05 \x01(\t\"0\n\rresponseTorre\x12\x0e\n\x06\x65stado\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\"B\n\x0c\x64\x61taDespegue\x12\x0f\n\x07\x64\x65stino\x18\x01 \x01(\t\x12\x11\n\taerolinea\x18\x02 \x01(\t\x12\x0e\n\x06\x63odigo\x18\x03 \x01(\t\"e\n\x10responseDespegue\x12\x0e\n\x06\x65stado\x18\x01 \x01(\x08\x12\x11\n\tipdestino\x18\x02 \x01(\t\x12\x0f\n\x07mensaje\x18\x03 \x01(\t\x12\r\n\x05pista\x18\x04 \x01(\x05\x12\x0e\n\x06\x61ltura\x18\x05 \x01(\x05\"n\n\x0e\x64\x61taAterrizaje\x12\x11\n\taerolinea\x18\x01 \x01(\t\x12\x0e\n\x06\x63odigo\x18\x02 \x01(\t\x12\x0f\n\x07pesoMax\x18\x03 \x01(\x05\x12\x11\n\tCapTanque\x18\x04 \x01(\x05\x12\x15\n\ripTorreActual\x18\x05 \x01(\t\"d\n\x12responseAterrizaje\x12\x0e\n\x06\x65stado\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\x12\x0e\n\x06puerta\x18\x03 \x01(\x05\x12\r\n\x05pista\x18\x04 \x01(\x05\x12\x0e\n\x06\x61ltura\x18\x05 \x01(\x05\"\x1e\n\x0b\x64\x61taDestino\x12\x0f\n\x07\x64\x65stino\x18\x01 \x01(\t\"!\n\x0fresponseDestino\x12\x0e\n\x06\x65stado\x18\x01 \x01(\x08\x32\xe4\x01\n\x03\x41PI\x12/\n\x0f\x44\x61tosHaciatorre\x12\n.dataAvion\x1a\x0e.responseTorre\"\x00\x12\x34\n\x10\x43omprobarDestino\x12\x0c.dataDestino\x1a\x10.responseDestino\"\x00\x12\x37\n\x11SolicitarDespegue\x12\r.dataDespegue\x1a\x11.responseDespegue\"\x00\x12=\n\x13SolicitarAterrizaje\x12\x0f.dataAterrizaje\x1a\x13.responseAterrizaje\"\x00\x62\x06proto3')
)




_DATAAVION = _descriptor.Descriptor(
  name='dataAvion',
  full_name='dataAvion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='aerolinea', full_name='dataAvion.aerolinea', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='codigo', full_name='dataAvion.codigo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pesoMax', full_name='dataAvion.pesoMax', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CapTanque', full_name='dataAvion.CapTanque', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ipTorreInicial', full_name='dataAvion.ipTorreInicial', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=125,
)


_RESPONSETORRE = _descriptor.Descriptor(
  name='responseTorre',
  full_name='responseTorre',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='estado', full_name='responseTorre.estado', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mensaje', full_name='responseTorre.mensaje', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=175,
)


_DATADESPEGUE = _descriptor.Descriptor(
  name='dataDespegue',
  full_name='dataDespegue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='destino', full_name='dataDespegue.destino', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aerolinea', full_name='dataDespegue.aerolinea', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='codigo', full_name='dataDespegue.codigo', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=243,
)


_RESPONSEDESPEGUE = _descriptor.Descriptor(
  name='responseDespegue',
  full_name='responseDespegue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='estado', full_name='responseDespegue.estado', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ipdestino', full_name='responseDespegue.ipdestino', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mensaje', full_name='responseDespegue.mensaje', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pista', full_name='responseDespegue.pista', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altura', full_name='responseDespegue.altura', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=346,
)


_DATAATERRIZAJE = _descriptor.Descriptor(
  name='dataAterrizaje',
  full_name='dataAterrizaje',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='aerolinea', full_name='dataAterrizaje.aerolinea', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='codigo', full_name='dataAterrizaje.codigo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pesoMax', full_name='dataAterrizaje.pesoMax', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CapTanque', full_name='dataAterrizaje.CapTanque', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ipTorreActual', full_name='dataAterrizaje.ipTorreActual', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=458,
)


_RESPONSEATERRIZAJE = _descriptor.Descriptor(
  name='responseAterrizaje',
  full_name='responseAterrizaje',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='estado', full_name='responseAterrizaje.estado', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mensaje', full_name='responseAterrizaje.mensaje', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='puerta', full_name='responseAterrizaje.puerta', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pista', full_name='responseAterrizaje.pista', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altura', full_name='responseAterrizaje.altura', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=460,
  serialized_end=560,
)


_DATADESTINO = _descriptor.Descriptor(
  name='dataDestino',
  full_name='dataDestino',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='destino', full_name='dataDestino.destino', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=562,
  serialized_end=592,
)


_RESPONSEDESTINO = _descriptor.Descriptor(
  name='responseDestino',
  full_name='responseDestino',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='estado', full_name='responseDestino.estado', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=594,
  serialized_end=627,
)

DESCRIPTOR.message_types_by_name['dataAvion'] = _DATAAVION
DESCRIPTOR.message_types_by_name['responseTorre'] = _RESPONSETORRE
DESCRIPTOR.message_types_by_name['dataDespegue'] = _DATADESPEGUE
DESCRIPTOR.message_types_by_name['responseDespegue'] = _RESPONSEDESPEGUE
DESCRIPTOR.message_types_by_name['dataAterrizaje'] = _DATAATERRIZAJE
DESCRIPTOR.message_types_by_name['responseAterrizaje'] = _RESPONSEATERRIZAJE
DESCRIPTOR.message_types_by_name['dataDestino'] = _DATADESTINO
DESCRIPTOR.message_types_by_name['responseDestino'] = _RESPONSEDESTINO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

dataAvion = _reflection.GeneratedProtocolMessageType('dataAvion', (_message.Message,), dict(
  DESCRIPTOR = _DATAAVION,
  __module__ = 'metadatos_pb2'
  # @@protoc_insertion_point(class_scope:dataAvion)
  ))
_sym_db.RegisterMessage(dataAvion)

responseTorre = _reflection.GeneratedProtocolMessageType('responseTorre', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSETORRE,
  __module__ = 'metadatos_pb2'
  # @@protoc_insertion_point(class_scope:responseTorre)
  ))
_sym_db.RegisterMessage(responseTorre)

dataDespegue = _reflection.GeneratedProtocolMessageType('dataDespegue', (_message.Message,), dict(
  DESCRIPTOR = _DATADESPEGUE,
  __module__ = 'metadatos_pb2'
  # @@protoc_insertion_point(class_scope:dataDespegue)
  ))
_sym_db.RegisterMessage(dataDespegue)

responseDespegue = _reflection.GeneratedProtocolMessageType('responseDespegue', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEDESPEGUE,
  __module__ = 'metadatos_pb2'
  # @@protoc_insertion_point(class_scope:responseDespegue)
  ))
_sym_db.RegisterMessage(responseDespegue)

dataAterrizaje = _reflection.GeneratedProtocolMessageType('dataAterrizaje', (_message.Message,), dict(
  DESCRIPTOR = _DATAATERRIZAJE,
  __module__ = 'metadatos_pb2'
  # @@protoc_insertion_point(class_scope:dataAterrizaje)
  ))
_sym_db.RegisterMessage(dataAterrizaje)

responseAterrizaje = _reflection.GeneratedProtocolMessageType('responseAterrizaje', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEATERRIZAJE,
  __module__ = 'metadatos_pb2'
  # @@protoc_insertion_point(class_scope:responseAterrizaje)
  ))
_sym_db.RegisterMessage(responseAterrizaje)

dataDestino = _reflection.GeneratedProtocolMessageType('dataDestino', (_message.Message,), dict(
  DESCRIPTOR = _DATADESTINO,
  __module__ = 'metadatos_pb2'
  # @@protoc_insertion_point(class_scope:dataDestino)
  ))
_sym_db.RegisterMessage(dataDestino)

responseDestino = _reflection.GeneratedProtocolMessageType('responseDestino', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEDESTINO,
  __module__ = 'metadatos_pb2'
  # @@protoc_insertion_point(class_scope:responseDestino)
  ))
_sym_db.RegisterMessage(responseDestino)



_API = _descriptor.ServiceDescriptor(
  name='API',
  full_name='API',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=630,
  serialized_end=858,
  methods=[
  _descriptor.MethodDescriptor(
    name='DatosHaciatorre',
    full_name='API.DatosHaciatorre',
    index=0,
    containing_service=None,
    input_type=_DATAAVION,
    output_type=_RESPONSETORRE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ComprobarDestino',
    full_name='API.ComprobarDestino',
    index=1,
    containing_service=None,
    input_type=_DATADESTINO,
    output_type=_RESPONSEDESTINO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SolicitarDespegue',
    full_name='API.SolicitarDespegue',
    index=2,
    containing_service=None,
    input_type=_DATADESPEGUE,
    output_type=_RESPONSEDESPEGUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SolicitarAterrizaje',
    full_name='API.SolicitarAterrizaje',
    index=3,
    containing_service=None,
    input_type=_DATAATERRIZAJE,
    output_type=_RESPONSEATERRIZAJE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_API)

DESCRIPTOR.services_by_name['API'] = _API

# @@protoc_insertion_point(module_scope)
